FROM mcr.microsoft.com/dotnet/sdk:10.0 AS deps
WORKDIR /src
COPY ["backend.slnx", "."]
COPY ["Backend.Core/Backend.Core.csproj", "Backend.Core/"]
COPY ["Backend.Infrastructure.PostgreSQL/Backend.Infrastructure.PostgreSQL.csproj", "Backend.Infrastructure.PostgreSQL/"]
COPY ["Backend.Web/Backend.Web.csproj", "Backend.Web/"]
RUN dotnet restore "backend.slnx"

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS development
WORKDIR /app
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
COPY --from=deps /root/.nuget /root/.nuget
COPY . .
ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--project", "Backend.Web/Backend.Web.csproj"]
