//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class BairrosClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://localhost:8080";
    }

    getBairros(search: string | null | undefined, page: number | undefined, pageSize: number | undefined): Promise<ResultadoPaginadoOfBairroResumoDto> {
        let url_ = this.baseUrl + "/api/localizacao/bairros?";
        if (search !== undefined && search !== null)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetBairros(_response);
        });
    }

    protected processGetBairros(response: Response): Promise<ResultadoPaginadoOfBairroResumoDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ResultadoPaginadoOfBairroResumoDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoPaginadoOfBairroResumoDto>(null as any);
    }

    createBairro(dto: CreateBairroDto): Promise<ResultadoOfBairros> {
        let url_ = this.baseUrl + "/api/localizacao/bairros";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateBairro(_response);
        });
    }

    protected processCreateBairro(response: Response): Promise<ResultadoOfBairros> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = ResultadoOfBairros.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoOfBairros>(null as any);
    }

    getBairro(id: number): Promise<Bairros> {
        let url_ = this.baseUrl + "/api/localizacao/bairros/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetBairro(_response);
        });
    }

    protected processGetBairro(response: Response): Promise<Bairros> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Bairros.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Bairros>(null as any);
    }

    updateBairro(id: number, dto: UpdateBairroDto): Promise<ResultadoOfBairros> {
        let url_ = this.baseUrl + "/api/localizacao/bairros/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateBairro(_response);
        });
    }

    protected processUpdateBairro(response: Response): Promise<ResultadoOfBairros> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ResultadoOfBairros.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoOfBairros>(null as any);
    }

    deleteBairro(id: number): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/localizacao/bairros/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteBairro(_response);
        });
    }

    protected processDeleteBairro(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

export class CidadesClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://localhost:8080";
    }

    getCidades(search: string | null | undefined, page: number | undefined, pageSize: number | undefined): Promise<ResultadoPaginadoOfCidadeResumoDto> {
        let url_ = this.baseUrl + "/api/localizacao/cidades?";
        if (search !== undefined && search !== null)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetCidades(_response);
        });
    }

    protected processGetCidades(response: Response): Promise<ResultadoPaginadoOfCidadeResumoDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ResultadoPaginadoOfCidadeResumoDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoPaginadoOfCidadeResumoDto>(null as any);
    }

    createCidade(dto: CreateCidadeDto): Promise<ResultadoOfCidades> {
        let url_ = this.baseUrl + "/api/localizacao/cidades";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateCidade(_response);
        });
    }

    protected processCreateCidade(response: Response): Promise<ResultadoOfCidades> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = ResultadoOfCidades.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoOfCidades>(null as any);
    }

    getCidade(id: number): Promise<Cidades> {
        let url_ = this.baseUrl + "/api/localizacao/cidades/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetCidade(_response);
        });
    }

    protected processGetCidade(response: Response): Promise<Cidades> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Cidades.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Cidades>(null as any);
    }

    updateCidade(id: number, dto: UpdateCidadeDto): Promise<ResultadoOfCidades> {
        let url_ = this.baseUrl + "/api/localizacao/cidades/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateCidade(_response);
        });
    }

    protected processUpdateCidade(response: Response): Promise<ResultadoOfCidades> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ResultadoOfCidades.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoOfCidades>(null as any);
    }

    deleteCidade(id: number): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/localizacao/cidades/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteCidade(_response);
        });
    }

    protected processDeleteCidade(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

export class EstadosClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://localhost:8080";
    }

    getEstados(search: string | null | undefined, page: number | undefined, pageSize: number | undefined): Promise<ResultadoPaginadoOfEstadoResumoDto> {
        let url_ = this.baseUrl + "/api/localizacao/estados?";
        if (search !== undefined && search !== null)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetEstados(_response);
        });
    }

    protected processGetEstados(response: Response): Promise<ResultadoPaginadoOfEstadoResumoDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ResultadoPaginadoOfEstadoResumoDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoPaginadoOfEstadoResumoDto>(null as any);
    }

    createEstado(dto: CreateEstadoDto): Promise<ResultadoOfEstados> {
        let url_ = this.baseUrl + "/api/localizacao/estados";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateEstado(_response);
        });
    }

    protected processCreateEstado(response: Response): Promise<ResultadoOfEstados> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = ResultadoOfEstados.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoOfEstados>(null as any);
    }

    getEstado(id: number): Promise<Estados> {
        let url_ = this.baseUrl + "/api/localizacao/estados/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetEstado(_response);
        });
    }

    protected processGetEstado(response: Response): Promise<Estados> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Estados.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Estados>(null as any);
    }

    updateEstado(id: number, dto: UpdateEstadoDto): Promise<ResultadoOfEstados> {
        let url_ = this.baseUrl + "/api/localizacao/estados/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateEstado(_response);
        });
    }

    protected processUpdateEstado(response: Response): Promise<ResultadoOfEstados> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ResultadoOfEstados.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoOfEstados>(null as any);
    }

    deleteEstado(id: number): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/localizacao/estados/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteEstado(_response);
        });
    }

    protected processDeleteEstado(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

export class PaisesClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://localhost:8080";
    }

    getPaises(search: string | null | undefined, page: number | undefined, pageSize: number | undefined): Promise<ResultadoPaginadoOfPaisResumoDto> {
        let url_ = this.baseUrl + "/api/localizacao/paises?";
        if (search !== undefined && search !== null)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetPaises(_response);
        });
    }

    protected processGetPaises(response: Response): Promise<ResultadoPaginadoOfPaisResumoDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ResultadoPaginadoOfPaisResumoDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoPaginadoOfPaisResumoDto>(null as any);
    }

    createPais(dto: CreatePaisDto): Promise<ResultadoOfPaises> {
        let url_ = this.baseUrl + "/api/localizacao/paises";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreatePais(_response);
        });
    }

    protected processCreatePais(response: Response): Promise<ResultadoOfPaises> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = ResultadoOfPaises.fromJS(resultData201);
            return result201;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoOfPaises>(null as any);
    }

    getPais(id: number): Promise<Paises> {
        let url_ = this.baseUrl + "/api/localizacao/paises/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetPais(_response);
        });
    }

    protected processGetPais(response: Response): Promise<Paises> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = Paises.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Paises>(null as any);
    }

    updatePais(id: number, dto: UpdatePaisDto): Promise<ResultadoOfPaises> {
        let url_ = this.baseUrl + "/api/localizacao/paises/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdatePais(_response);
        });
    }

    protected processUpdatePais(response: Response): Promise<ResultadoOfPaises> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ResultadoOfPaises.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ResultadoOfPaises>(null as any);
    }

    deletePais(id: number): Promise<FileResponse> {
        let url_ = this.baseUrl + "/api/localizacao/paises/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
                "Accept": "application/octet-stream"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeletePais(_response);
        });
    }

    protected processDeletePais(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

export class ResultadoPaginadoOfBairroResumoDto implements IResultadoPaginadoOfBairroResumoDto {
    itens?: BairroResumoDto[];
    totalDeItens?: number;
    paginaAtual?: number;
    tamanhoDaPagina?: number;
    totalDePaginas?: number;
    temPaginaAnterior?: boolean;
    temProximaPagina?: boolean;

    constructor(data?: IResultadoPaginadoOfBairroResumoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["itens"])) {
                this.itens = [] as any;
                for (let item of _data["itens"])
                    this.itens!.push(BairroResumoDto.fromJS(item));
            }
            this.totalDeItens = _data["totalDeItens"];
            this.paginaAtual = _data["paginaAtual"];
            this.tamanhoDaPagina = _data["tamanhoDaPagina"];
            this.totalDePaginas = _data["totalDePaginas"];
            this.temPaginaAnterior = _data["temPaginaAnterior"];
            this.temProximaPagina = _data["temProximaPagina"];
        }
    }

    static fromJS(data: any): ResultadoPaginadoOfBairroResumoDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoPaginadoOfBairroResumoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.itens)) {
            data["itens"] = [];
            for (let item of this.itens)
                data["itens"].push(item ? item.toJSON() : undefined as any);
        }
        data["totalDeItens"] = this.totalDeItens;
        data["paginaAtual"] = this.paginaAtual;
        data["tamanhoDaPagina"] = this.tamanhoDaPagina;
        data["totalDePaginas"] = this.totalDePaginas;
        data["temPaginaAnterior"] = this.temPaginaAnterior;
        data["temProximaPagina"] = this.temProximaPagina;
        return data;
    }
}

export interface IResultadoPaginadoOfBairroResumoDto {
    itens?: BairroResumoDto[];
    totalDeItens?: number;
    paginaAtual?: number;
    tamanhoDaPagina?: number;
    totalDePaginas?: number;
    temPaginaAnterior?: boolean;
    temProximaPagina?: boolean;
}

export class BairroResumoDto implements IBairroResumoDto {
    id?: number;
    bairro?: string;
    cidadeId?: number;
    cidadeNome?: string;
    uf?: string;

    constructor(data?: IBairroResumoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.bairro = _data["bairro"];
            this.cidadeId = _data["cidadeId"];
            this.cidadeNome = _data["cidadeNome"];
            this.uf = _data["uf"];
        }
    }

    static fromJS(data: any): BairroResumoDto {
        data = typeof data === 'object' ? data : {};
        let result = new BairroResumoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["bairro"] = this.bairro;
        data["cidadeNome"] = this.cidadeNome;
        data["uf"] = this.uf;
        return data;
    }
}

export interface IBairroResumoDto {
    id?: number;
    bairro?: string;
    cidadeId?: number;
    cidadeNome?: string;
    uf?: string;
}

export class Bairros implements IBairros {
    id?: number;
    bairro?: string;
    cidade?: Cidades;

    constructor(data?: IBairros) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.bairro = _data["bairro"];
            this.cidade = _data["cidade"] ? Cidades.fromJS(_data["cidade"]) : undefined as any;
        }
    }

    static fromJS(data: any): Bairros {
        data = typeof data === 'object' ? data : {};
        let result = new Bairros();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["bairro"] = this.bairro;
        data["cidade"] = this.cidade ? this.cidade.toJSON() : undefined as any;
        return data;
    }
}

export interface IBairros {
    id?: number;
    bairro?: string;
    cidade?: Cidades;
}

export class Cidades implements ICidades {
    id?: number;
    cidade?: string;
    ddd?: number;
    estado?: Estados;

    constructor(data?: ICidades) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.cidade = _data["cidade"];
            this.ddd = _data["ddd"];
            this.estado = _data["estado"] ? Estados.fromJS(_data["estado"]) : undefined as any;
        }
    }

    static fromJS(data: any): Cidades {
        data = typeof data === 'object' ? data : {};
        let result = new Cidades();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["cidade"] = this.cidade;
        data["ddd"] = this.ddd;
        data["estado"] = this.estado ? this.estado.toJSON() : undefined as any;
        return data;
    }
}

export interface ICidades {
    id?: number;
    cidade?: string;
    ddd?: number;
    estado?: Estados;
}

export class Estados implements IEstados {
    id?: number;
    estado?: string;
    uf?: string;
    pais?: Paises;

    constructor(data?: IEstados) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.estado = _data["estado"];
            this.uf = _data["uf"];
            this.pais = _data["pais"] ? Paises.fromJS(_data["pais"]) : undefined as any;
        }
    }

    static fromJS(data: any): Estados {
        data = typeof data === 'object' ? data : {};
        let result = new Estados();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["estado"] = this.estado;
        data["uf"] = this.uf;
        data["pais"] = this.pais ? this.pais.toJSON() : undefined as any;
        return data;
    }
}

export interface IEstados {
    id?: number;
    estado?: string;
    uf?: string;
    pais?: Paises;
}

export class Paises implements IPaises {
    id?: number;
    ddi?: string;
    siglaIso?: string;
    moeda?: string;
    simboloMoeda?: string;
    pais?: string;

    constructor(data?: IPaises) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.ddi = _data["ddi"];
            this.siglaIso = _data["siglaIso"];
            this.moeda = _data["moeda"];
            this.simboloMoeda = _data["simboloMoeda"];
            this.pais = _data["pais"];
        }
    }

    static fromJS(data: any): Paises {
        data = typeof data === 'object' ? data : {};
        let result = new Paises();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["ddi"] = this.ddi;
        data["siglaIso"] = this.siglaIso;
        data["moeda"] = this.moeda;
        data["simboloMoeda"] = this.simboloMoeda;
        data["pais"] = this.pais;
        return data;
    }
}

export interface IPaises {
    id?: number;
    ddi?: string;
    siglaIso?: string;
    moeda?: string;
    simboloMoeda?: string;
    pais?: string;
}

export class ResultadoOfBairros implements IResultadoOfBairros {
    success?: boolean;
    data?: Bairros | undefined;
    errors?: ResultadoErro[] | undefined;

    constructor(data?: IResultadoOfBairros) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.data = _data["data"] ? Bairros.fromJS(_data["data"]) : undefined as any;
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(ResultadoErro.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ResultadoOfBairros {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoOfBairros();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["data"] = this.data ? this.data.toJSON() : undefined as any;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IResultadoOfBairros {
    success?: boolean;
    data?: Bairros | undefined;
    errors?: ResultadoErro[] | undefined;
}

export class ResultadoErro implements IResultadoErro {
    code?: string;
    message?: string;
    field?: string | undefined;

    constructor(data?: IResultadoErro) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            this.message = _data["message"];
            this.field = _data["field"];
        }
    }

    static fromJS(data: any): ResultadoErro {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoErro();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["message"] = this.message;
        data["field"] = this.field;
        return data;
    }
}

export interface IResultadoErro {
    code?: string;
    message?: string;
    field?: string | undefined;
}

export class CreateBairroDto implements ICreateBairroDto {
    bairro?: string;
    cidadeId?: number;

    constructor(data?: ICreateBairroDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.bairro = _data["bairro"];
            this.cidadeId = _data["cidadeId"];
        }
    }

    static fromJS(data: any): CreateBairroDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateBairroDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["bairro"] = this.bairro;
        data["cidadeId"] = this.cidadeId;
        return data;
    }
}

export interface ICreateBairroDto {
    bairro?: string;
    cidadeId?: number;
}

export class UpdateBairroDto implements IUpdateBairroDto {
    bairro?: string;
    cidadeId?: number;

    constructor(data?: IUpdateBairroDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.bairro = _data["bairro"];
            this.cidadeId = _data["cidadeId"];
        }
    }

    static fromJS(data: any): UpdateBairroDto {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateBairroDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["bairro"] = this.bairro;
        data["cidadeId"] = this.cidadeId;
        return data;
    }
}

export interface IUpdateBairroDto {
    bairro?: string;
    cidadeId?: number;
}

export class ResultadoPaginadoOfCidadeResumoDto implements IResultadoPaginadoOfCidadeResumoDto {
    itens?: CidadeResumoDto[];
    totalDeItens?: number;
    paginaAtual?: number;
    tamanhoDaPagina?: number;
    totalDePaginas?: number;
    temPaginaAnterior?: boolean;
    temProximaPagina?: boolean;

    constructor(data?: IResultadoPaginadoOfCidadeResumoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["itens"])) {
                this.itens = [] as any;
                for (let item of _data["itens"])
                    this.itens!.push(CidadeResumoDto.fromJS(item));
            }
            this.totalDeItens = _data["totalDeItens"];
            this.paginaAtual = _data["paginaAtual"];
            this.tamanhoDaPagina = _data["tamanhoDaPagina"];
            this.totalDePaginas = _data["totalDePaginas"];
            this.temPaginaAnterior = _data["temPaginaAnterior"];
            this.temProximaPagina = _data["temProximaPagina"];
        }
    }

    static fromJS(data: any): ResultadoPaginadoOfCidadeResumoDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoPaginadoOfCidadeResumoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.itens)) {
            data["itens"] = [];
            for (let item of this.itens)
                data["itens"].push(item ? item.toJSON() : undefined as any);
        }
        data["totalDeItens"] = this.totalDeItens;
        data["paginaAtual"] = this.paginaAtual;
        data["tamanhoDaPagina"] = this.tamanhoDaPagina;
        data["totalDePaginas"] = this.totalDePaginas;
        data["temPaginaAnterior"] = this.temPaginaAnterior;
        data["temProximaPagina"] = this.temProximaPagina;
        return data;
    }
}

export interface IResultadoPaginadoOfCidadeResumoDto {
    itens?: CidadeResumoDto[];
    totalDeItens?: number;
    paginaAtual?: number;
    tamanhoDaPagina?: number;
    totalDePaginas?: number;
    temPaginaAnterior?: boolean;
    temProximaPagina?: boolean;
}

export class CidadeResumoDto implements ICidadeResumoDto {
    id?: number;
    cidade?: string;
    ddd?: number;
    estadoId?: number;
    estadoNome?: string;
    uf?: string;

    constructor(data?: ICidadeResumoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.cidade = _data["cidade"];
            this.ddd = _data["ddd"];
            this.estadoId = _data["estadoId"];
            this.estadoNome = _data["estadoNome"];
            this.uf = _data["uf"];
        }
    }

    static fromJS(data: any): CidadeResumoDto {
        data = typeof data === 'object' ? data : {};
        let result = new CidadeResumoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["cidade"] = this.cidade;
        data["ddd"] = this.ddd;
        data["estadoNome"] = this.estadoNome;
        data["uf"] = this.uf;
        return data;
    }
}

export interface ICidadeResumoDto {
    id?: number;
    cidade?: string;
    ddd?: number;
    estadoNome?: string;
    uf?: string;
}

export class ResultadoOfCidades implements IResultadoOfCidades {
    success?: boolean;
    data?: Cidades | undefined;
    errors?: ResultadoErro[] | undefined;

    constructor(data?: IResultadoOfCidades) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.data = _data["data"] ? Cidades.fromJS(_data["data"]) : undefined as any;
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(ResultadoErro.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ResultadoOfCidades {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoOfCidades();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["data"] = this.data ? this.data.toJSON() : undefined as any;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IResultadoOfCidades {
    success?: boolean;
    data?: Cidades | undefined;
    errors?: ResultadoErro[] | undefined;
}

export class CreateCidadeDto implements ICreateCidadeDto {
    cidade?: string;
    ddd?: number;
    estadoId?: number;

    constructor(data?: ICreateCidadeDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.cidade = _data["cidade"];
            this.ddd = _data["ddd"];
            this.estadoId = _data["estadoId"];
        }
    }

    static fromJS(data: any): CreateCidadeDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateCidadeDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["cidade"] = this.cidade;
        data["ddd"] = this.ddd;
        data["estadoId"] = this.estadoId;
        return data;
    }
}

export interface ICreateCidadeDto {
    cidade?: string;
    ddd?: number;
    estadoId?: number;
}

export class UpdateCidadeDto implements IUpdateCidadeDto {
    cidade?: string;
    ddd?: number;
    estadoId?: number;

    constructor(data?: IUpdateCidadeDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.cidade = _data["cidade"];
            this.ddd = _data["ddd"];
            this.estadoId = _data["estadoId"];
        }
    }

    static fromJS(data: any): UpdateCidadeDto {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateCidadeDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["cidade"] = this.cidade;
        data["ddd"] = this.ddd;
        data["estadoId"] = this.estadoId;
        return data;
    }
}

export interface IUpdateCidadeDto {
    cidade?: string;
    ddd?: number;
    estadoId?: number;
}

export class ResultadoPaginadoOfEstadoResumoDto implements IResultadoPaginadoOfEstadoResumoDto {
    itens?: EstadoResumoDto[];
    totalDeItens?: number;
    paginaAtual?: number;
    tamanhoDaPagina?: number;
    totalDePaginas?: number;
    temPaginaAnterior?: boolean;
    temProximaPagina?: boolean;

    constructor(data?: IResultadoPaginadoOfEstadoResumoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["itens"])) {
                this.itens = [] as any;
                for (let item of _data["itens"])
                    this.itens!.push(EstadoResumoDto.fromJS(item));
            }
            this.totalDeItens = _data["totalDeItens"];
            this.paginaAtual = _data["paginaAtual"];
            this.tamanhoDaPagina = _data["tamanhoDaPagina"];
            this.totalDePaginas = _data["totalDePaginas"];
            this.temPaginaAnterior = _data["temPaginaAnterior"];
            this.temProximaPagina = _data["temProximaPagina"];
        }
    }

    static fromJS(data: any): ResultadoPaginadoOfEstadoResumoDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoPaginadoOfEstadoResumoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.itens)) {
            data["itens"] = [];
            for (let item of this.itens)
                data["itens"].push(item ? item.toJSON() : undefined as any);
        }
        data["totalDeItens"] = this.totalDeItens;
        data["paginaAtual"] = this.paginaAtual;
        data["tamanhoDaPagina"] = this.tamanhoDaPagina;
        data["totalDePaginas"] = this.totalDePaginas;
        data["temPaginaAnterior"] = this.temPaginaAnterior;
        data["temProximaPagina"] = this.temProximaPagina;
        return data;
    }
}

export interface IResultadoPaginadoOfEstadoResumoDto {
    itens?: EstadoResumoDto[];
    totalDeItens?: number;
    paginaAtual?: number;
    tamanhoDaPagina?: number;
    totalDePaginas?: number;
    temPaginaAnterior?: boolean;
    temProximaPagina?: boolean;
}

export class EstadoResumoDto implements IEstadoResumoDto {
    id?: number;
    estado?: string;
    uf?: string;
    paisId?: number;
    paisNome?: string;

    constructor(data?: IEstadoResumoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.estado = _data["estado"];
            this.uf = _data["uf"];
            this.paisId = _data["paisId"];
            this.paisNome = _data["paisNome"];
        }
    }

    static fromJS(data: any): EstadoResumoDto {
        data = typeof data === 'object' ? data : {};
        let result = new EstadoResumoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["estado"] = this.estado;
        data["uf"] = this.uf;
        data["paisNome"] = this.paisNome;
        return data;
    }
}

export interface IEstadoResumoDto {
    id?: number;
    estado?: string;
    uf?: string;
    paisId?: number;
    paisNome?: string;
}

export class ResultadoOfEstados implements IResultadoOfEstados {
    success?: boolean;
    data?: Estados | undefined;
    errors?: ResultadoErro[] | undefined;

    constructor(data?: IResultadoOfEstados) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.data = _data["data"] ? Estados.fromJS(_data["data"]) : undefined as any;
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(ResultadoErro.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ResultadoOfEstados {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoOfEstados();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["data"] = this.data ? this.data.toJSON() : undefined as any;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IResultadoOfEstados {
    success?: boolean;
    data?: Estados | undefined;
    errors?: ResultadoErro[] | undefined;
}

export class CreateEstadoDto implements ICreateEstadoDto {
    estado?: string;
    uf?: string;
    paisId?: number;

    constructor(data?: ICreateEstadoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.estado = _data["estado"];
            this.uf = _data["uf"];
            this.paisId = _data["paisId"];
        }
    }

    static fromJS(data: any): CreateEstadoDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateEstadoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["estado"] = this.estado;
        data["uf"] = this.uf;
        data["paisId"] = this.paisId;
        return data;
    }
}

export interface ICreateEstadoDto {
    estado?: string;
    uf?: string;
    paisId?: number;
}

export class UpdateEstadoDto implements IUpdateEstadoDto {
    estado?: string;
    uf?: string;
    paisId?: number;

    constructor(data?: IUpdateEstadoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.estado = _data["estado"];
            this.uf = _data["uf"];
            this.paisId = _data["paisId"];
        }
    }

    static fromJS(data: any): UpdateEstadoDto {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateEstadoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["estado"] = this.estado;
        data["uf"] = this.uf;
        data["paisId"] = this.paisId;
        return data;
    }
}

export interface IUpdateEstadoDto {
    estado?: string;
    uf?: string;
    paisId?: number;
}

export class ResultadoPaginadoOfPaisResumoDto implements IResultadoPaginadoOfPaisResumoDto {
    itens?: PaisResumoDto[];
    totalDeItens?: number;
    paginaAtual?: number;
    tamanhoDaPagina?: number;
    totalDePaginas?: number;
    temPaginaAnterior?: boolean;
    temProximaPagina?: boolean;

    constructor(data?: IResultadoPaginadoOfPaisResumoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["itens"])) {
                this.itens = [] as any;
                for (let item of _data["itens"])
                    this.itens!.push(PaisResumoDto.fromJS(item));
            }
            this.totalDeItens = _data["totalDeItens"];
            this.paginaAtual = _data["paginaAtual"];
            this.tamanhoDaPagina = _data["tamanhoDaPagina"];
            this.totalDePaginas = _data["totalDePaginas"];
            this.temPaginaAnterior = _data["temPaginaAnterior"];
            this.temProximaPagina = _data["temProximaPagina"];
        }
    }

    static fromJS(data: any): ResultadoPaginadoOfPaisResumoDto {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoPaginadoOfPaisResumoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.itens)) {
            data["itens"] = [];
            for (let item of this.itens)
                data["itens"].push(item ? item.toJSON() : undefined as any);
        }
        data["totalDeItens"] = this.totalDeItens;
        data["paginaAtual"] = this.paginaAtual;
        data["tamanhoDaPagina"] = this.tamanhoDaPagina;
        data["totalDePaginas"] = this.totalDePaginas;
        data["temPaginaAnterior"] = this.temPaginaAnterior;
        data["temProximaPagina"] = this.temProximaPagina;
        return data;
    }
}

export interface IResultadoPaginadoOfPaisResumoDto {
    itens?: PaisResumoDto[];
    totalDeItens?: number;
    paginaAtual?: number;
    tamanhoDaPagina?: number;
    totalDePaginas?: number;
    temPaginaAnterior?: boolean;
    temProximaPagina?: boolean;
}

export class PaisResumoDto implements IPaisResumoDto {
    id?: number;
    pais?: string;
    siglaIso?: string;
    ddi?: string;
    moeda?: string;
    simboloMoeda?: string;

    constructor(data?: IPaisResumoDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.pais = _data["pais"];
            this.siglaIso = _data["siglaIso"];
            this.ddi = _data["ddi"];
            this.moeda = _data["moeda"];
            this.simboloMoeda = _data["simboloMoeda"];
        }
    }

    static fromJS(data: any): PaisResumoDto {
        data = typeof data === 'object' ? data : {};
        let result = new PaisResumoDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["pais"] = this.pais;
        data["siglaIso"] = this.siglaIso;
        data["ddi"] = this.ddi;
        data["moeda"] = this.moeda;
        data["simboloMoeda"] = this.simboloMoeda;
        return data;
    }
}

export interface IPaisResumoDto {
    id?: number;
    pais?: string;
    siglaIso?: string;
    ddi?: string;
    moeda?: string;
    simboloMoeda?: string;
}

export class ResultadoOfPaises implements IResultadoOfPaises {
    success?: boolean;
    data?: Paises | undefined;
    errors?: ResultadoErro[] | undefined;

    constructor(data?: IResultadoOfPaises) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["success"];
            this.data = _data["data"] ? Paises.fromJS(_data["data"]) : undefined as any;
            if (Array.isArray(_data["errors"])) {
                this.errors = [] as any;
                for (let item of _data["errors"])
                    this.errors!.push(ResultadoErro.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ResultadoOfPaises {
        data = typeof data === 'object' ? data : {};
        let result = new ResultadoOfPaises();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["success"] = this.success;
        data["data"] = this.data ? this.data.toJSON() : undefined as any;
        if (Array.isArray(this.errors)) {
            data["errors"] = [];
            for (let item of this.errors)
                data["errors"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IResultadoOfPaises {
    success?: boolean;
    data?: Paises | undefined;
    errors?: ResultadoErro[] | undefined;
}

export class CreatePaisDto implements ICreatePaisDto {
    ddi?: string;
    siglaIso?: string;
    moeda?: string;
    simboloMoeda?: string;
    pais?: string;

    constructor(data?: ICreatePaisDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.ddi = _data["ddi"];
            this.siglaIso = _data["siglaIso"];
            this.moeda = _data["moeda"];
            this.simboloMoeda = _data["simboloMoeda"];
            this.pais = _data["pais"];
        }
    }

    static fromJS(data: any): CreatePaisDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreatePaisDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ddi"] = this.ddi;
        data["siglaIso"] = this.siglaIso;
        data["moeda"] = this.moeda;
        data["simboloMoeda"] = this.simboloMoeda;
        data["pais"] = this.pais;
        return data;
    }
}

export interface ICreatePaisDto {
    ddi?: string;
    siglaIso?: string;
    moeda?: string;
    simboloMoeda?: string;
    pais?: string;
}

export class UpdatePaisDto implements IUpdatePaisDto {
    ddi?: string;
    siglaIso?: string;
    moeda?: string;
    simboloMoeda?: string;
    pais?: string;

    constructor(data?: IUpdatePaisDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.ddi = _data["ddi"];
            this.siglaIso = _data["siglaIso"];
            this.moeda = _data["moeda"];
            this.simboloMoeda = _data["simboloMoeda"];
            this.pais = _data["pais"];
        }
    }

    static fromJS(data: any): UpdatePaisDto {
        data = typeof data === 'object' ? data : {};
        let result = new UpdatePaisDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ddi"] = this.ddi;
        data["siglaIso"] = this.siglaIso;
        data["moeda"] = this.moeda;
        data["simboloMoeda"] = this.simboloMoeda;
        data["pais"] = this.pais;
        return data;
    }
}

export interface IUpdatePaisDto {
    ddi?: string;
    siglaIso?: string;
    moeda?: string;
    simboloMoeda?: string;
    pais?: string;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}
