SET search_path TO projeto_sistemas;

CREATE TABLE IF NOT EXISTS marcas (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  marca VARCHAR(120) NOT NULL UNIQUE,
  descricao VARCHAR(255),
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);
