SET search_path TO projeto_sistemas;

INSERT INTO paises (ddi, codigo_iso_pais, codigo_iso_moeda, simbolo_moeda, pais)
VALUES
  ('55', 'BRA', 'BRL', 'R$', 'BRASIL')
ON CONFLICT (codigo_iso_pais) DO NOTHING;

INSERT INTO estados (pais_id, estado, uf)
SELECT id, 'ACRE', 'AC' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'ALAGOAS', 'AL' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'AMAPÁ', 'AP' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'AMAZONAS', 'AM' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'BAHIA', 'BA' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'CEARÁ', 'CE' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'DISTRITO FEDERAL', 'DF' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'ESPÍRITO SANTO', 'ES' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'GOIÁS', 'GO' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'MARANHÃO', 'MA' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'MATO GROSSO', 'MT' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'MATO GROSSO DO SUL', 'MS' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'MINAS GERAIS', 'MG' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'PARÁ', 'PA' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'PARAÍBA', 'PB' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'PARANÁ', 'PR' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'PERNAMBUCO', 'PE' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'PIAUÍ', 'PI' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'RIO DE JANEIRO', 'RJ' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'RIO GRANDE DO NORTE', 'RN' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'RIO GRANDE DO SUL', 'RS' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'RONDÔNIA', 'RO' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'RORAIMA', 'RR' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'SANTA CATARINA', 'SC' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'SÃO PAULO', 'SP' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'SERGIPE', 'SE' FROM paises WHERE pais = 'BRASIL'
UNION ALL
SELECT id, 'TOCANTINS', 'TO' FROM paises WHERE pais = 'BRASIL'
ON CONFLICT (pais_id, uf) DO NOTHING;