SET search_path TO projeto_sistemas;

CREATE TABLE IF NOT EXISTS nfes (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  chave_acesso VARCHAR(44) UNIQUE,
  numero INTEGER NOT NULL,
  serie SMALLINT NOT NULL,
  data_emissao TIMESTAMP NOT NULL,
  data_saida TIMESTAMP,
  emitente_id INTEGER NOT NULL,
  emitente_nome_razaosocial VARCHAR(150) NOT NULL,
  emitente_cpf_cnpj VARCHAR(20) NOT NULL,
  emitente_rg_ie VARCHAR(20),
  emitente_apelido_nomefantasia VARCHAR(100),
  emitente_endereco VARCHAR(150),
  emitente_bairro VARCHAR(100),
  emitente_telefone VARCHAR(20),
  emitente_email VARCHAR(254),
  cliente_id INTEGER NOT NULL,
  cliente_nome_razaosocial VARCHAR(150) NOT NULL,
  cliente_cpf_cnpj VARCHAR(20) NOT NULL,
  cliente_rg_ie VARCHAR(20),
  cliente_apelido_nomefantasia VARCHAR(100),
  cliente_endereco VARCHAR(150),
  cliente_bairro VARCHAR(100),
  cliente_telefone VARCHAR(20),
  cliente_email VARCHAR(254),
  tipo_operacao tipo_operacao_enum NOT NULL,
  status_nfe status_nfe_enum NOT NULL DEFAULT 'RASCUNHO',
  transportadora_id INTEGER,
  valor_produtos NUMERIC(14, 2) NOT NULL DEFAULT 0,
  valor_desconto NUMERIC(14, 2) NOT NULL DEFAULT 0,
  valor_frete NUMERIC(14, 2) NOT NULL DEFAULT 0,
  valor_seguro NUMERIC(14, 2) NOT NULL DEFAULT 0,
  valor_outras_despesas NUMERIC(14, 2) NOT NULL DEFAULT 0,
  valor_total NUMERIC(14, 2) NOT NULL DEFAULT 0,
  CONSTRAINT nfes_emitente_fk FOREIGN KEY (emitente_id) REFERENCES emitentes (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT nfes_emitente_snapshot_fk FOREIGN KEY (emitente_id, emitente_cpf_cnpj, emitente_nome_razaosocial) REFERENCES emitentes (id, cpf_cnpj, nome_razaosocial) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT nfes_cliente_fk FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT nfes_cliente_snapshot_fk FOREIGN KEY (cliente_id, cliente_cpf_cnpj, cliente_nome_razaosocial) REFERENCES clientes (id, cpf_cnpj, nome_razaosocial) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT nfes_transportadora_fk FOREIGN KEY (transportadora_id) REFERENCES transportadoras (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT nfes_emitente_serie_numero_unique UNIQUE (emitente_id, serie, numero),
  CONSTRAINT nfes_emitente_nome_not_empty_ck CHECK (LENGTH(TRIM(emitente_nome_razaosocial)) > 0),
  CONSTRAINT nfes_emitente_cpf_cnpj_not_empty_ck CHECK (LENGTH(TRIM(emitente_cpf_cnpj)) > 0),
  CONSTRAINT nfes_cliente_nome_not_empty_ck CHECK (LENGTH(TRIM(cliente_nome_razaosocial)) > 0),
  CONSTRAINT nfes_cliente_cpf_cnpj_not_empty_ck CHECK (LENGTH(TRIM(cliente_cpf_cnpj)) > 0),
  CONSTRAINT nfes_chave_acesso_fluxo_ck CHECK (
    (status_nfe = 'RASCUNHO' AND chave_acesso IS NULL)
    OR (status_nfe IN ('EMITIDA', 'CANCELADA') AND chave_acesso ~ '^[0-9]{44}$')
  ),
  CONSTRAINT nfes_valor_produtos_ck CHECK (valor_produtos >= 0),
  CONSTRAINT nfes_valor_desconto_ck CHECK (valor_desconto >= 0),
  CONSTRAINT nfes_valor_frete_ck CHECK (valor_frete >= 0),
  CONSTRAINT nfes_valor_seguro_ck CHECK (valor_seguro >= 0),
  CONSTRAINT nfes_valor_outras_ck CHECK (valor_outras_despesas >= 0),
  CONSTRAINT nfes_valor_total_ck CHECK (valor_total >= 0)
);
